### PR TITLE
Fix writing of curriculum metrics to CSV

### LINKED ISSUE #8: `write_csv` fails to create curriculum csv file with metrics
The issue is with the `course_line()` function in `csv_utilities.py`:

https://github.com/SheepTester-forks/CurricularAnalytics.py/blob/917465ad221336707510af140e01350b47d0dbd1/curricularanalytics/csv_utilities.py#L56

The function is calling `.course_complexity()`, etc. (which does not exist) instead of `complexity()` .

Additionally, I believe there needs to be a leading comma to correctly add in the new metrics columns.

image

### PR DESCRIPTION
**Pull request by will-hou**
Resolves #8 

Also matches the formatting of the metrics file exported by curricular analytics more closely:

* Complexity displayed to one decimal place
* Delay factor displayed to one decimal place
* Course credit hours displayed as a whole integer

### CODE REVIEW

**Comment by will-hou** [comment]
Testing with the public VCU Public [Computer Engineering curriculum](https://curricularanalytics.org/curriculums/31354)

Left is file with metrics downloaded from Curricular Analytics. Right is file _without_ metrics downloaded from Curricular analytics and processed with `CurricularAnalytics.py`

Only differences are the ordering of pre-reqs but I don't believe that is important (also out of scope for this PR)

image

**Comment by SheepTester** [comment]
I'm not sure if we should match Curricular Analytics exactly since unit counts at some universities aren't necessarily an integer. For example, UCSD's language classes are 2.5 units

**Comment by will-hou** [comment]
> I'm not sure if we should match Curricular Analytics exactly since unit counts at some universities aren't necessarily an integer. For example, UCSD's language classes are 2.5 units

Ah didn't know that. I removed that change

**Comment by will-hou** [comment]
@SheepTester Are there any other items you want me to address before this can get merged? Thanks!

**Pull request merged**
